spring:
    datasource:
      url: jdbc:mysql://localhost:3306/rentalI?createNewDatabaseIfNotExist=true
      username: root
      password: 1234

    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true